
print("cemi saxelia mariami")
print("cemi dis saxelia nuca")
print("me 13 wlis var")
print("goa is the best")
print("my friand's name is sako")
print(69)
print("cemi megobris saxelia ani")
print(62)
print("me vcxovrov tbilisi")
print(727)
print("me goashi vswavlob")
print(14)
print("simagleshi 160 var")
print("nika keshelava sauketesoa")
print("group62")
print("aura+50")
print(76)
print("umm")